version: '3.8'

services:
    # Nginx Service
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        networks:
            - laravel

    # PHP-FPM Service
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - PHP_IDE_CONFIG=serverName=laravel
        networks:
            - laravel

    # MySQL Service
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            -   redis_data:/data
        networks:
            - laravel

    # PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: laravel
        depends_on:
            - mysql
        networks:
            - laravel


# Networks
networks:
    laravel:
        driver: bridge

# Volumes
volumes:
    mysql_data:
    redis_data:
