name: CI

on:
  push:
    branches: [ "dev" ]

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIV_KEY }}
          script: "cd ${{vars.PROJECT_PATH}} && dep deploy"
