name: CI

on:
  push:
    branches: [ "dev" ]

jobs:
  dev_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.DEV_HOST }}
          username: deployer
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          script: "cd ${{vars.DEV_PROJECT_PATH}} && dep deploy"
